### PR TITLE
Test against core objectstore_transfer2 branch

### PR DESCRIPTION
**Pull request by phil-davis**
To see if all unit tests from https://github.com/owncloud/core/pull/36464 are passing in object storage.

### CODE REVIEW

**Comment by phil-davis** [comment]
All 9899 core unit tests are passing - great!

**Comment by jvillafanez** [comment]
Note that the previously offending test (https://github.com/owncloud/core/blob/master/apps/files_versions/tests/VersioningTest.php#L135) creates the users randomly, so it's possible that both users end up using the same bucket. In this case, the problem we have won't be triggered.

I'm not sure how to make this more consistent. The users should be probably generated by the files_primary_s3 app somehow, even though the users will be used by the core's versioning tests.

**Comment by phil-davis** [comment]
The latest run of CI is all green. That is good news.
I guess we can run it multiple times.
And also somehow find a way to ensure that the different users are forced into different buckets during the tests?

**Comment by jvillafanez** [comment]
> And also somehow find a way to ensure that the different users are forced into different buckets during the tests?

Maybe you can try to use something like https://github.com/owncloud/files_primary_s3/pull/276 (maybe we can move it here and delete the other PR?)
The idea is to use a different mapper so at least we can ensure (with a high probability) that 2 consecutive users will end up in different buckets.

**Comment by phil-davis** [comment]
The related core PR was merged a while ago. Closing this.

**Pull request closed without merging**
