### PR TITLE
add app icon

### PR DESCRIPTION
**Pull request by hurradieweltgehtunter**
In addition to the new app images the icons get updated, too.
@mmattel @pmaier1

### CODE REVIEW

**Comment by phil-davis** [comment]
@hurradieweltgehtunter I noticed this sitting here since 2019. Should this be done, or close?

**Comment by hurradieweltgehtunter** [comment]
There was a discussion whether to use colored icons or not. AFAIK this was never decided. @pmaier1 can you says sth about this?

**Comment by pmaier1** [comment]
Well, I always voted for consistency. All apps have greyscale app icons that fit with the overall design in the product. Why introduce colored ones?

**Comment by JammingBen** [comment]
Closing for now as it does not follow our grey-white-scheme.

**Pull request closed without merging**
