### PR TITLE
Ready for 10.1

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
> I don't get the failure yet

wrong php version hitting the code base - will work on it ....

**Comment by DeepDiver1975** [comment]
> wrong php version hitting the code base - will work on it ....

related to owncloudci/core image running php7 - master requires 7.1 min.

**Comment by DeepDiver1975** [comment]
furthermore there seems to be an issue with bower: https://drone.owncloud.com/owncloud/files_primary_s3/181/16

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
touch build/node_modules
build/node_modules/bower/bin/bower install
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option
Makefile:161: recipe for target 'core/vendor' failed
make: *** [core/vendor] Error 1

**Comment by patrickjahns** [comment]
Bower issue addressed here https://github.com/owncloud-ci/core/pull/5

**Comment by DeepDiver1975** [comment]
@patrickjahns ready to go noe - review please? THX

**Pull request merged**
