### PR TITLE
Verisoned buckets

### PR DESCRIPTION
**Pull request by DeepDiver1975**
requires https://github.com/owncloud/core/pull/29607

### CODE REVIEW

**Comment by butonic** [comment]
versioning itself works \o/

- [ ] preview icon is not changed after restoring a version because the post_write hook is not triggered

The MetaFileVersionNode seems to operate on the root storage, not the users home. I had to hack it to emit a hook with the correct relative path:
```
diff --git a/lib/private/Files/Meta/MetaFileVersionNode.php b/lib/private/Files/Meta/MetaFileVersionNode.php
index 4ab1b29..5c283cc 100644
--- a/lib/private/Files/Meta/MetaFileVersionNode.php
+++ b/lib/private/Files/Meta/MetaFileVersionNode.php
@@ -106,7 +106,19 @@ class MetaFileVersionNode extends AbstractFile implements IProvidesAdditionalHea
                        if (!$target->isUpdateable()) {
                                throw new ForbiddenException("Cannot write to $targetPath", false);
                        }
-                       return $this->storage->restoreVersion($this->internalPath, $this->versionId);
+                       $result = $this->storage->restoreVersion($this->internalPath, $this->versionId);
+                       //FIXME the nodes are resolved relative to root, which means they are accessed via the root storage, not the users home storages
+                       $relativePath = $target->getInternalPath();
+                       // FIXME remove hack to feed the correct relative path to the preview generation
+                       if (substr($relativePath, 0, 6) == 'files/') {
+                               $relativePath = substr($relativePath, 6);
+                       }
+                       \OC_Hook::emit('\OCP\Versions', 'rollback', [
+                               'path' => $relativePath,
+                               'user' => $target->getOwner()->getUID(),
+                               'revision' => $this->versionId, // TODO revision != versionId, but unused in previews code ... the only code in core listening for this hook
+                       ]);
+                       return $result;
                }

                // for now we only allow restoring of a version
```
The storage of restoreVersion() is an ObjectStoreStorage, not a HomeObjectStoreStorage. That works only by accident. Something is fishy here... 


- [ ] previews don't work in the versions list:

```
preview:1 GET http://localhost:8000/oc/core/index.php/apps/files_versions/preview?file=%2Fwelcome.txt&version=1511951920 404 (Not Found)

  | Image (async) |   |  
-- | -- | -- | --
  | (anonymous) | @ | jquery.js:5221
  | domManip | @ | jquery.js:5414
  | append | @ | jquery.js:5218
  | _onAddModel | @ | versionstabview.js?v…a84471fbf73853c:153
  | triggerEvents | @ | backbone.js?v=bce669…a84471fbf73853c:371
  | triggerApi | @ | backbone.js?v=bce669…a84471fbf73853c:356
  | eventsApi | @ | backbone.js?v=bce669…a84471fbf73853c:155
  | Events.trigger | @ | backbone.js?v=bce669…a84471fbf73853c:346
  | _onModelEvent | @ | backbone.js?v=bce669…84471fbf73853c:1155
  | triggerEvents | @ | backbone.js?v=bce669…a84471fbf73853c:372
  | triggerApi | @ | backbone.js?v=bce669…a84471fbf73853c:357
  | eventsApi | @ | backbone.js?v=bce669…a84471fbf73853c:155
  | Events.trigger | @ | backbone.js?v=bce669…a84471fbf73853c:346
  | set | @ | backbone.js?v=bce669…a84471fbf73853c:913
  | options.success | @ | backbone.js?v=bce669…84471fbf73853c:1026
  | (anonymous) | @ | oc-backbone-webdav.j…a84471fbf73853c:173
  | Promise resolved (async) |   |  
  | callPropFind | @ | oc-backbone-webdav.j…a84471fbf73853c:163
  | davCall | @ | oc-backbone-webdav.j…a84471fbf73853c:316
  | davSync | @ | oc-backbone-webdav.j…a84471fbf73853c:429
  | fetch | @ | backbone.js?v=bce669…84471fbf73853c:1031
  | success | @ | versionstabview.js?v…a84471fbf73853c:102
  | (anonymous) | @ | versionmodel.js?v=bc…ba84471fbf73853c:32
  | j | @ | jquery.js:3099
  | fireWith | @ | jquery.js:3211
  | e.(anonymous function) | @ | jquery.js:3301
  | (anonymous) | @ | client.js?v=bce66933…a84471fbf73853c:743
  | Promise resolved (async) |   |  
  | _moveOrCopy | @ | client.js?v=bce66933…a84471fbf73853c:740
  | copy | @ | client.js?v=bce66933…a84471fbf73853c:803
  | revert | @ | versionmodel.js?v=bc…ba84471fbf73853c:29
  | _onClickRevertVersion | @ | versionstabview.js?v…ba84471fbf73853c:96
  | dispatch | @ | jquery.js:4435
  | r.handle | @ | jquery.js:4121
```

**Comment by DeepDiver1975** [comment]
> preview icon is not changed after restoring a version because the post_write hook is not triggered

there is a branch in core to fix previews - unrelated to this

**Comment by DeepDiver1975** [comment]
> The MetaFileVersionNode seems to operate on the root storage, not the users home. I had to hack it to emit a hook with the correct relative path:

I was not emitting the hook my intention - its not needed from my pov ...

**Comment by butonic** [comment]
the preview stuff relies on it to delete all previews. without it the old prieview will still be used (because the `c` query param is not used ... or rather only as a cache buster)

**Comment by DeepDiver1975** [comment]
> the preview stuff relies on it to delete all previews. without it the old prieview will still be used (because the c query param is not used ... or rather only as a cache buster)

I'll have a look at this in the preview branch

**Pull request merged**
