### PR TITLE
Run acceptance tests including notifications

### PR DESCRIPTION
**Pull request by phil-davis**
Run the API and webUI acceptance tests by cloning and installing the ``notifications`` app, then the ``core`` scenarios "do their thing" and enable the notifications app for scenarios that need it.

See also #79 for an alternate approach.

### CODE REVIEW

**Comment by phil-davis** [comment]
@DeepDiver1975 ?
Some PHPunit tests fail:
```
There were 4 errors:

1) Test\Share20\ManagerTest::testTransferShare with data set #1 ('user')
OCP\Files\StorageNotAvailableException: 

/drone/server/lib/private/Files/Storage/Wrapper/Availability.php:75
/drone/server/lib/private/Files/Storage/Wrapper/Availability.php:457
/drone/server/lib/private/Files/Storage/Wrapper/Checksum.php:202
/drone/server/lib/private/Files/ObjectStore/NoopScanner.php:59
/drone/server/lib/private/Files/View.php:1364
/drone/server/lib/private/Files/View.php:1405
/drone/server/lib/private/Files/Node/Root.php:188
/drone/server/lib/private/Files/Node/Root.php:361
/drone/server/lib/private/Server.php:1016
/drone/server/tests/lib/Share20/ManagerTest.php:1711

2) Test\Share20\ManagerTest::testTransferShare with data set #2 ('anotherusertest')
OCP\Files\StorageNotAvailableException: 

/drone/server/lib/private/Files/Storage/Wrapper/Availability.php:75
/drone/server/lib/private/Files/Storage/Wrapper/Availability.php:457
/drone/server/lib/private/Files/Storage/Wrapper/Checksum.php:202
/drone/server/lib/private/Files/ObjectStore/NoopScanner.php:59
/drone/server/lib/private/Files/View.php:1364
/drone/server/lib/private/Files/View.php:1405
/drone/server/lib/private/Files/Node/Root.php:188
/drone/server/lib/private/Files/Node/Root.php:361
/drone/server/lib/private/Server.php:1016
/drone/server/tests/lib/Share20/ManagerTest.php:1711

3) Test\Share20\ManagerTest::testTransferShare with data set #3 ('group')
OCP\Files\StorageNotAvailableException: 

/drone/server/lib/private/Files/Storage/Wrapper/Availability.php:75
/drone/server/lib/private/Files/Storage/Wrapper/Availability.php:457
/drone/server/lib/private/Files/Storage/Wrapper/Checksum.php:202
/drone/server/lib/private/Files/ObjectStore/NoopScanner.php:59
/drone/server/lib/private/Files/View.php:1364
/drone/server/lib/private/Files/View.php:1405
/drone/server/lib/private/Files/Node/Root.php:188
/drone/server/lib/private/Files/Node/Root.php:361
/drone/server/lib/private/Server.php:1016
/drone/server/tests/lib/Share20/ManagerTest.php:1711

4) Test\Share20\ManagerTest::testTransferShare with data set #4 ('remote')
OCP\Files\StorageNotAvailableException: 

/drone/server/lib/private/Files/Storage/Wrapper/Availability.php:75
/drone/server/lib/private/Files/Storage/Wrapper/Availability.php:457
/drone/server/lib/private/Files/Storage/Wrapper/Checksum.php:202
/drone/server/lib/private/Files/ObjectStore/NoopScanner.php:59
/drone/server/lib/private/Files/View.php:1364
/drone/server/lib/private/Files/View.php:1405
/drone/server/lib/private/Files/Node/Root.php:188
/drone/server/lib/private/Files/Node/Root.php:361
/drone/server/lib/private/Server.php:1016
/drone/server/tests/lib/Share20/ManagerTest.php:1711

--

There was 1 failure:

1) Test\Encryption\DecryptAllTest::testDecryptFileForFileId
Failed asserting that 56 matches expected 57.

/drone/server/tests/lib/Encryption/DecryptAllTest.php:558

--
```
I don't think that they are broken by the acceptance test code.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/files_primary_s3/305/61
drone job got canceled, it looks like after 3 hours total elapsed time.
1) The job takes about 30 minutes to set itself up, including >20 minutes in install-core.
2) Running all webUI test scenarios in a single run takes "a long time".

Do we extend the drone job max timeout to 4 hours? Or sort out something to run tests in smaller pieces?

One idea, if we do not want to go back to running all the "little" individual suites separately. We could easily tag each of the existing ``@webUI`` features with an extra tag to say which part of a split the feature is in - ``@webUI-1`` ``@webUI-2`` ``@webUI-3`` ``@webUI-4`` ... We could agree some number of parts that we split the ``webUI`` tests into (e.g. 8). Then any other app like ``files_primary_s3`` can run 8 parts in 8 jobs. At the moment these jobs would be about 20-30 minutes each. For some significant time into the future they would be <1 hour. So ``core`` can re-organize the logical suites, but maintain this "tagging convention API" of providing a breakup of the ``webUI`` tests into 8 parts. Thus ``.drone.yml`` in apps would not need to change.

Similar could be done for API scenarios/features to reduce their elapsed time which is >2 hours.

**Comment by patrickjahns** [comment]
Setup time can be put down by setting proper composer cache // using nigthly tarballs.

I see a problem with using tags to split the suites again - someone might forget to tag the scenario and then it won't be run?

For now let's bump the time limit and put this splitting into a separate ticket for the backlog

**Comment by phil-davis** [comment]
This is a little demonstration of how it can be done quite easily if you want to run the notifications ``core`` tests from another app. 
For ``files_primary_s3`` the tags approach in #79 has been chosen.
So closing this PR.

**Pull request closed without merging**
