### PR TITLE
[Tests-Only][CI] fix the starlark code for reduced ci after merge and sonarcloud

### PR DESCRIPTION
**Pull request by dpakach**
fix the starlark code for reduced ci after merge and sonarcloud

issue https://github.com/owncloud/QA/issues/649

### CODE REVIEW

**Comment by phil-davis** [comment]
This repo does not currently have coverage enabled on any unit test pipelines. The drone starlark does not currently cope with that combination - unit tests exist, but there is no coverage.

I will enable coverage, because that should be useful!

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/files_primary_s3/1995/6/8
The unit test coverage output file does not have the "standard" location/name.
Need to look into that.

**Comment by dpakach** [comment]
@phil-davis this app runs the unit tests from core, I copied the phpunit.xml from core to get this working without introducing any additional changes on the default .drone.star code
One problem that creates is that there is a duplicate of the phpunit file from core and that needs to be updated if any changes happen in that file of core.

**Comment by phil-davis** [comment]
This has been done in PR #441 
CI after merge does not run the acceptance tests - for example https://drone.owncloud.com/owncloud/files_primary_s3/2297
CI after merge does do SonarCloud analysis https://drone.owncloud.com/owncloud/files_primary_s3/2297/15/7
There is SonarCloud analysis at https://sonarcloud.io/dashboard?id=owncloud_files_primary_s3

Looks good - closing this issue.

**Pull request closed without merging**
