### PR TITLE
su-exec www-data is not needed for acceptance tests

### PR DESCRIPTION
**Pull request by phil-davis**

### CODE REVIEW

**Comment by patrickjahns** [comment]
With #120 merged you should be good to go

**Comment by patrickjahns** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by phil-davis** [comment]
It works.
@patrickjahns review/approve?

**Pull request merged**
