### PR TITLE
[WIP]  running api/ui acceptance tests 

### PR DESCRIPTION
**Pull request by patrickjahns**
First try to run the full api / webui suite towards the new objectstorage implementation

Tasks:
- [x] get api tests running
- [x] get webui tests running
- [ ] validate failures and check if they should be skipped on objectstorage as it might not be relevant / applicaple

### CODE REVIEW

**Comment by mrow4a** [comment]
Any progress in here?

**Comment by patrickjahns** [comment]
@mrow4a 
Exactly what progress do you expect after 24 hours on a weekend?

**Comment by mrow4a** [comment]
Omg, I did not notice this PR has 2 days, sorry for that! Just saw WIP and did not check the dates.

**Comment by DeepDiver1975** [comment]
> /drone/server/tests/acceptance/features/apiMain/checksums.feature:65

201 is expected and 204 is returned - this happens if the file already existed ... needs debugging ....

**Comment by DeepDiver1975** [comment]
> /drone/server/tests/acceptance/features/apiMain/comments.feature:25 /drone/server/tests/acceptance/features/apiMain/comments.feature:33 /drone/server/tests/acceptance/features/apiMain/comments.feature:44

comments seem to add up - delete not working?

**Comment by individual-it** [comment]
split the tests in suites and added mailhog

**Comment by patrickjahns** [comment]
Before we finally merge, let's evaluate if we need/want to follow the splitting of test suites in apps as well. 
As any change to the testing suite in core (separation of steps etc.) would then need to be performed also on more repositories ( encryption, files_primary_s3, objectstore(?), swift )

**Comment by individual-it** [comment]
Not splitting the suites gets us an endless long, not parallelizeble job
@phil-davis thoughts?

**Comment by phil-davis** [comment]
For core, while still running IE11 and Edge on Travis, we have to keep the webUI suites reasonably small so they keep well withing the Travis 50 minute job limit.

In general, we want an individual job in drone to run in 5 to 15 minutes. That way we always have the chance to provide fast results if we wish, by adding many drone workers.

For these apps that are "back-end plugin things, we want to run all (or as many as possible) core acceptance tests. So we need all the suites.

If there was a way to ``include`` some file/s from core into ``.drone.yml`` then we could design a system where some standard drone steps and matrix entries are in separate files and core and these type of apps can include them.

**Comment by patrickjahns** [comment]
> Not splitting the suites gets us an endless long, not parallelizable job

> In general, we want an individual job in drone to run in 5 to 15 minutes. That way we always have the chance to provide fast results if we wish, by adding many drone workers.

This definitely holds true for core - as there is more maintainer work to be done, compared to separate apps. On core - maintainers are a lot more confronted with rebasing - whereas in these apps there is less "concurrent" development happening.

The development turnaround on files_primary_s3, encryption etc. will be very low compared to core. Most runs in these apps will be "nightly" runs. I don't see the requirement here to have parallelization. Timeouts (as in jenkins / saucelabs) will not hit us on drone, as we can define our time limits ourself

> For these apps that are "back-end plugin things, we want to run all (or as many as possible) core acceptance tests. So we need all the suites.

Agreed

> If there was a way to include some file/s from core into .drone.yml then we could design a system where some standard drone steps and matrix entries are in separate files and core and these type of apps can include them.

This is not possible - there is no way of modifying a pipeline "on-the-fly". The pipeline needs to be computed before it can actually run - including files from other sources would require to fetch/clone these resources first.

**Comment by phil-davis** [comment]
``apiProvisioning`` was split into 2 pieces last week:
``apiProvisioning-v1``
``apiProvisioning-v2``

I pushed a commit here to do that.

This will be a nuisance for apps that are "backend plugins" and just want to run the whole set of core acceptance test suites. It would be nice to be able to include a list of matrix entries from core somehow.

**Comment by phil-davis** [comment]
apiProvisioning suites are passing now.

**Comment by patrickjahns** [comment]
> This will be a nuisance for apps that are "backend plugins" and just want to run the whole set of core acceptance test suites. It would be nice to be able to include a list of matrix entries from core somehow.

please see above - this is technically not possible - a `.drone.yml` is per repository. 
The `git clone` step follows only after the `.drone.yml` has been fetched from github and thus it is not possible to include arbitrary steps

Hence the recommendation to have it run as one suite?

**Comment by patrickjahns** [comment]
The federated acceptance tests run currently also on an object store - should we also consider the scenario:
non-objectstore owncloud user federates to objectstore-owncloud user?
objectstore-owncloud user federates to non-objectstore user?

**Comment by DeepDiver1975** [comment]
> non-objectstore owncloud user federates to objectstore-owncloud user?
> objectstore-owncloud user federates to non-objectstore user?

I see no necessity for this - the federated servers are decoupled via http/webdav and we are testing both sides with and without objectstore

**Comment by phil-davis** [comment]
1 long suite for API tests works fine. I do not have confidence that the webdriver-selenium-browser communications chain will reliably stay up for the whole webUI tests in a single run (but I guess we should try!)

The downside I see is that running API in a single serial job and webUI in another single serial job, each job will take significant time (and even more time if it is all run together in 1 job). There is no chance to reduce the elapsed turn-around time by adding drone workers. When someone wants a "quick" result from CI (for hotfix, or as "last-minute" things are done before tagging a release...) then it will take time.

**Comment by patrickjahns** [comment]
superseeded by #58

**Pull request closed without merging**
