### PR TITLE
[tests-only] Apply latest drone starlark code

### PR DESCRIPTION
**Pull request by phil-davis**
These changes had been made recently in the activity app, but not applied here in files_primary_s3.
That caused me a bit of confusion - working in both apps!

Apply the latest `.drone.star` changes here.

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCeph-29-5-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2367/51/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCeph-29-6-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2367/52/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCeph-29-13-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2367/59/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCeph-29-7-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2367/53/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCeph-29-12-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2367/58/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCeph-29-9-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2367/55/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCeph-29-8-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2367/54/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCeph-29-14-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2367/60/1

**Comment by phil-davis** [comment]
drone got "service are not ready in 10 minutes" - pulling some images failed or was very slow.
I restarted CI.

**Review by individual-it — APPROVED** [review]

**Pull request merged**
