### PR TITLE
Standardize CI setup

### LINKED ISSUE #116: make test-php-style
For harmonisation, it would be good to have a ``make test-php-style`` as we have eg in core.
Please see also documentation: https://github.com/owncloud/documentation/issues/4064#issuecomment-412053981 plus follow up comment

This would: 
- ease up development
- have a documentation that matches different repo setups

@phil-davis @DeepDiver1975 

Part of https://github.com/owncloud/QA/issues/582

### PR DESCRIPTION
**Pull request by skshetry**
Standardize CI for `owncloud/files_primary_s3`.

Fixes #116. 

- [x] Use make in drone

### CODE REVIEW

**Comment by skshetry** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by skshetry** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by skshetry** [comment]
@ownclouders rebase

**Comment by ownclouders** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by skshetry** [comment]
Split tests into multiple parts           
                                                                                                     1
Currently, we have web UI tests split into 8 parts. But, even then, the tests run for 3-4 hours, due to which we are getting 'code integrity errors'. Thus, this doubles the
partitions for web UI which hopefully will remove the errors. API tests are happy for now, so I have left as it is for now.

P.S: Integrity errors appear after the tests have been running for 30-35 mins."

**Comment by phil-davis** [comment]
Rebased and resolved conflict in ``.drone.yml``

**Comment by phil-davis** [comment]
@skshetry I added some commits last night while trying to see what the problem was. Those commits just make some labels a bit more standard in ``.drone.yml``

The actual final fix was to core - PR https://github.com/owncloud/core/pull/33929 - it was not finding the list of core test suites correctly unless the script first did a ``cd`` to the core ``tests/acceptance`` directory. I managed to fix that in core last night in time to get it into the QA tarball.

I just restarted the drone job again for this PR. Earlier this morning it had some unrelated "git fetch" errors.

**Pull request merged**
