### PR TITLE
[tests-only] Use owncloudci/wait-for docker image

### PR DESCRIPTION
**Pull request by phil-davis**
Update the drone starlark code the same as https://github.com/owncloud/activity/pull/1036

I had to reduce the number of pipelines because of https://drone.owncloud.com/owncloud/files_primary_s3/2682
`starlark: maximum file size exceeded `

### CODE REVIEW

**Comment by phil-davis** [comment]
wait-for ceph works:
https://drone.owncloud.com/owncloud/files_primary_s3/2684/14/10
```
latest: Pulling from owncloudci/wait-for
Digest: sha256:08aa5a5f16c7997f37568efc087b4501afea851cfd0143d898e64e0eeb0310e3
Status: Image is up to date for owncloudci/wait-for:latest
+ wait-for -it ceph:80 -t 600
services are ready!
```

wait-for scality works:
https://drone.owncloud.com/owncloud/files_primary_s3/2684/70/15
```
latest: Pulling from owncloudci/wait-for
Digest: sha256:08aa5a5f16c7997f37568efc087b4501afea851cfd0143d898e64e0eeb0310e3
Status: Image is up to date for owncloudci/wait-for:latest
+ wait-for -it scality:8000 -t 600
services are ready!
```

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCeph-29-20-master-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2684/59/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiScality-29-1-master-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2684/69/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCeph-29-29-master-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2684/68/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCeph-29-28-master-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2684/67/1

**Review by kiranparajuli589 — COMMENTED** [review]
lgtm

**Review by kiranparajuli589 — APPROVED** [review]

**Pull request merged**
