### PR TITLE
[Tests-Only][CI] Update .drone.star file for new changes from activity app

### PR DESCRIPTION
**Pull request by dpakach**
Related https://github.com/owncloud/QA/issues/678
- Fix code coverage reporting
- Implement early fail and full-ci in drone CI behavior like what is done in core and other repos

**note** this PR was generated by a automated script

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/encryption/1985/68/18
```
time="2021-07-05T09:40:20Z" level=fatal msg="POST https://api.github.com/repos/owncloud/encryption/issues/294/comments: 422 Validation Failed [{Resource:IssueComment Field:data Code:unprocessable Message:Body cannot be blank}]" 
```

https://drone.owncloud.com/owncloud/encryption/1985/68/17
```
...
>> /drone/src/comments.file
```

The acceptance test step failed. The build-github-comment step is putting the comment text into a file in `drone/src`. But I suspect that the github-comment step has a default directory in a different place.

I will push a fix for that - probably it will need to be fixed in all oC10 apps!

**Comment by phil-davis** [comment]
I added a commit to remove the "scality ring 7" pipelines - fixes issue #452

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiCeph-32-24-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2344/72/1

**Comment by phil-davis** [comment]
core PR https://github.com/owncloud/core/pull/38922 was merged today. We are running the very latest test code from core master, that has changed tests for public link upload. But `daily-master-qa` only has core code from last night. So we get fails, the same as https://github.com/owncloud/encryption/pull/294#issuecomment-874069329

This should pass tomorrow, when `daily-master-qa` has been updated overnight.

**Pull request merged**
