### PR TITLE
[full-ci] [tests-only] Test all pipelines 20210728

### PR DESCRIPTION
**Pull request by phil-davis**
On top of #469 - run all the nightly pipelines to check that they work OK with the reformatted code.

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>api-scal-art-remote-8-5-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2399/172/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>api-scal8-remote-8-6-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2399/165/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>api-scal-art-remote-8-4-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2399/171/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>api-scal8-remote-8-7-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2399/166/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>api-scal-art-remote-8-1-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2399/168/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>api-scal8-remote-8-8-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2399/167/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>api-scal-art-remote-8-2-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2399/169/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>api-scal-art-remote-8-3-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2399/170/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>api-scal-art-remote-8-4-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2402/171/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>api-scal-art-remote-8-8-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2402/175/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>api-scal-art-remote-8-1-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2402/168/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>api-scal-art-remote-8-3-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2402/170/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>api-scal-art-remote-8-2-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2402/169/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>api-scal-art-remote-8-6-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2402/173/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>api-scal-art-remote-8-5-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2402/172/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>api-scal8-remote-8-1-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2402/160/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>api-scal8-remote-8-5-master-mariadb10.2-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/files_primary_s3/2402/164/1

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/files_primary_s3/2403/49/19
That is a known issue fixed by https://github.com/owncloud/core/pull/39073

**Comment by phil-davis** [comment]
The last commit fixes a problem with quoted strings in `sed` command. I cherry-picked it into PR #471 so it can be merged.

**Comment by phil-davis** [comment]
Finished with testing - all is good.

**Pull request closed without merging**
