### PR TITLE
Always provide return status for functions

### PR DESCRIPTION
**Pull request by sharidas**
Provide return status for writeObject method.
This would help to know if the upload to
object storage was successful or not.

Signed-off-by: Sujith H <sharidasan@owncloud.com>

### CODE REVIEW

**Comment by sharidas** [comment]
- [x] Required https://github.com/owncloud/core/pull/35116

**Comment by PVince81** [comment]
@patrickjahns will require to schedule a new release of this app

**Comment by PVince81** [comment]
@sharidas please provide test steps, even if it involves patching the code to make it fail

**Comment by sharidas** [comment]
Scenario addressed by this PR + https://github.com/owncloud/core/pull/35116

Scenario: The file uploaded would result in an entry in filecache and the file is missing in the objectstore.

How to reproduce it manually:
- Remove the changes in this PR + https://github.com/owncloud/core/pull/35116
- Now add a line `return;` in the beginning of the method `writeObject()` before https://github.com/owncloud/files_primary_s3/blob/master/lib/s3storage.php#L118;
- Upload the file
- Now the user would see an entry in the filecache table. Where as the objectstore will not have the file uploaded. The preview of the file will also be not shown in the UI
- No error will be reported in the Dev Tools -> network tab of the browser.

Remedy/Solution:
Now  apply the change of this PR + https://github.com/owncloud/core/pull/35116 ( remember to keep the `return;` mentioned in the steps above. 
- Upload a file
- The filecache entry will not be there for the file because the file didn't uploade to the objectstore.
- Bad request response will be seen in the browser's Dev tools -> network tab.

**Comment by VicDeo** [comment]
@PVince81 it's core-dependant, so only after the core part is backported to stable10

**Comment by patrickjahns** [comment]
@VicDeo - If that is the case, please note that the `min-version` of this app should be increased accordingly to match the correct core version

**Comment by sharidas** [comment]
I think we might have to revert this change, becasue there is a discussion  https://github.com/owncloud/core/pull/35116#issuecomment-487841336 ( read from here ). The core change would be to add an objectstorage upload fail exception. And in this app we will throw that exception instead of return `true` or `false`.

**Comment by sharidas** [comment]
Lets revert this change and will bring the exception changes in my next PR.

**Pull request merged**
